[project]
name = "gol"
version = "1.0.0"
requires-python = ">= 3.8"
dependencies = [
    "pandas >= 2.0.3"
]
readme = "README.md"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
